### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by bjorn3** [shepmaster/strata-rust#1]

**Comment by dtolnay** [comment]
I am wondering this as well :smiley_cat:. Everything I see here looks super promising but I have no idea what the vision is.

**Comment by shepmaster** [comment]
Oh, the vision is *amazing*, believe me! "I have discovered a truly remarkable vision which this margin is too small to contain". 

I'll try to get to this this week, I swear!

**Comment by mystor** [comment]
@shepmaster Do you intend to make the parser component independently usable as a library outside of the web app you seem to be making with it?

**Comment by shepmaster** [comment]
> the parser component independently usable

That I do! The main problem is that I haven't decided on a good name for it yet 😁

**Comment by shepmaster** [comment]
Since I've never had people interested in a project before I had a README, this is new to me, but is anyone interested in [reviewing the PR to add the README](https://github.com/shepmaster/strata-rust/pull/2)? I suppose if there are questions you have that I haven't answered, I might as well pick your brains now! 😇
